### ISSUE TITLE
bboxes as opencv input

### ISSUE THREAD

**Issue by vkieboominspark** [hhk7734/tensorflow-yolov4#16] opened 2020-07-23 09:26 UTC
What do you recommend in using for getting the bboxes/ROI for using with cv2.rectangle() function? So getting the original coordinates from yolo.predict()

**Comment by hhk7734** [comment] 2020-07-23 10:55
I am not sure what you want.

**Comment by vkieboominspark** [comment] 2020-07-23 11:00
Sorry, I meant the top left en bottom right corner of the detected bounding boxes as (x,y),(x,y) coordinates on original input image. Hope this clarifies.

**Comment by hhk7734** [comment] 2020-07-23 11:04
You want to draw coordinates as text on the image?

**Comment by vkieboominspark** [comment] 2020-07-23 11:18
No the rectangle itself, with the coordinates. And with opencv, so not the inference function.

**Comment by hhk7734** [comment] 2020-07-23 11:22
https://github.com/hhk7734/tensorflow-yolov4/blob/056697a748852f996e9b2f6209e892b4c03e0826/py_src/yolov4/tf/__init__.py#L180-L188

this is a part of `yolo.inference`, `self.predict` is `yolo.predict`

`yolo.draw_bboxes` draw coordinates as a rectangle.

**Comment by vkieboominspark** [comment] 2020-07-23 11:41
Ah I see. The 'convert ratio to lenght' part is where it is converted to the right format. Thank you.

**Comment by hhk7734** [comment] 2020-07-23 12:12
Aha :).
```python
bboxes = yolo.predict()
bboxes == [[center_x_ratio, center_y_ratio, width_ratio, height_ratio, class_id, probability], ...]
```

If the problem is solved, close the issue.

**Closed as completed** 2020-07-24 16:21 UTC
